### ISSUE TITLE
There was an error while trying to load the gem 'jsonapi_spec_helpers'

### ISSUE THREAD

**Issue by BjornMelgaard** [jsonapi-suite/jsonapi_suite#14]
I has this error, maybe its because of [this](https://github.com/jsonapi-suite/jsonapi_suite/blob/master/jsonapi_suite.gemspec#L26), not sure, better make `add_development_dependency`, though I fixed this with `require: false`

```
gem 'jsonapi_suite'
gem 'jsonapi-rails'

group :development, :test do
  gem 'jsonapi_spec_helpers', require: false
end
```

```
$ rails s
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'jsonapi_spec_helpers'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant RSpec::Matchers
Backtrace for gem load error is:
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/jsonapi_spec_helpers-0.4.0/lib/jsonapi_spec_helpers/matchers.rb:1:in `<top (required)>'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/jsonapi_spec_helpers-0.4.0/lib/jsonapi_spec_helpers.rb:3:in `<top (required)>'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
/home/bjorn/projects/ngrx-todolist/config/application.rb:17:in `<top (required)>'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:129:in `require'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:129:in `block in perform'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:126:in `tap'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:126:in `perform'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/railties-5.1.1/lib/rails/command/base.rb:63:in `perform'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/railties-5.1.1/lib/rails/command.rb:44:in `invoke'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
/home/bjorn/projects/ngrx-todolist/bin/rails:9:in `require'
/home/bjorn/projects/ngrx-todolist/bin/rails:9:in `<top (required)>'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
/home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
/home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/home/bjorn/projects/ngrx-todolist/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Bundler Error Backtrace:
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/bundler-1.14.6/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
        from /home/bjorn/projects/ngrx-todolist/config/application.rb:17:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:129:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:129:in `block in perform'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:126:in `tap'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:126:in `perform'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/railties-5.1.1/lib/rails/command/base.rb:63:in `perform'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/railties-5.1.1/lib/rails/command.rb:44:in `invoke'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
        from /home/bjorn/projects/ngrx-todolist/bin/rails:9:in `require'
        from /home/bjorn/projects/ngrx-todolist/bin/rails:9:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@ngrx-todolist/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
        from /home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /home/bjorn/projects/ngrx-todolist/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'

```

**Comment by richmolj** [comment]
```ruby
group :development, :test do
  gem 'jsonapi_spec_helpers', require: false
end
```

That code **should** be correct but right now please omit this and everything should work. The spec helpers are (incorrectly) coming with the main lib at the moment. It's an easy fix but I have to update all the guides as well and haven't gotten to it yet.

**Comment by richmolj** [comment]
Alternatively, keep it as you had and will work once I make the fix as well :)

**Comment by BjornMelgaard** [comment]
Get it)

**Comment by richmolj** [comment]
Issue has been fixed in latest version
