### ISSUE TITLE
`require': cannot load such file -- jsonapi/rails

### ISSUE THREAD

**Issue by bastianl** [jsonapi-suite/jsonapi_suite#4]
I'm trying to start a new rails project with jsonapi suite on `macOS 10.12.2`.

```
ruby 2.4.0
Rails 5.0.1
```

I've followed the doc instructions by adding `gem 'jsonapi_suite'` to my Gemfile. After running `bundle install` I get the following error:

```
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- jsonapi/rails (LoadError)
        from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/jsonapi_compliable-0.5.1/lib/jsonapi_compliable/rails.rb:1:in `<top (required)>'
        from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/jsonapi_compliable-0.5.1/lib/jsonapi_compliable.rb:24:in `<top (required)>'
        from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/jsonapi_suite-0.5.1/lib/jsonapi_suite.rb:5:in `<top (required)>'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:91:in `require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:86:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:86:in `block in require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:75:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:75:in `require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler.rb:106:in `require'
        from /Users/lennartbastian/web/test-json/config/application.rb:17:in `<top (required)>'
        from /usr/local/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:82:in `require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:82:in `preload'
        from /usr/local/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:143:in `serve'
        from /usr/local/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
        from /usr/local/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'```

**Comment by richmolj** [comment]
@bastianl you got me right as I was releasing a new version. Use `gem 'jsonapi_suite', '~> 0.4'` to get working right away, or follow the new guides I'll have out shortly ;)

**Comment by bastianl** [comment]
@richmolj sweet thanks!

**Comment by bastianl** [comment]
@richmolj `0.4` doesn't seem to be working, i'm getting the same error. Is it not referencing the correction version of `jsonapi_compatible`? Can you let me know when this is fixed?

**Comment by richmolj** [comment]
Whoops! My mistake - 0.2.1 is the latest working release of `jsonapi_suite`, which will lock compliable to `~> 0.4`. I'll give a note when docs are out for new version, won't be long now.

**Comment by bastianl** [comment]
@richmolj I actually tried `0.2.1` too, same issue. But thanks I'll give the new version a shot when its out.

**Comment by richmolj** [comment]
@bastianl That's bizzare. What version of `jsonapi_compliable` is in your `Gemfile.lock`?

FWIW, the solution in the new version is simply

```ruby
gem 'jsonapi-rails', require: 'jsonapi/rails'
```

As that's the error being thrown, maybe give it a shot anyway.

Moving this to an optional dependency as the new version makes Rails optional.

**Comment by bastianl** [comment]
Here is the relevant excerpt from `Gemfile.lock` It looks like `json_compliable` is being linked twice..
```
json (1.8.6)
    jsonapi (0.1.1.beta2)
      json (~> 1.8)
    jsonapi-renderer (0.1.1)
    jsonapi-serializable (0.1.1)
      jsonapi-renderer (= 0.1.1)
    jsonapi_compliable (0.5.1)
      jsonapi-serializable (~> 0.1)
    jsonapi_errorable (0.1.1)
      active_model_serializers (~> 0.10)
      rails (>= 4.1, < 6)
    jsonapi_spec_helpers (0.2.3)
    jsonapi_suite (0.2.1)
      jsonapi (= 0.1.1.beta2)
      jsonapi_compliable (~> 0.4)
      jsonapi_errorable (~> 0.1)
      jsonapi_spec_helpers (~> 0.2)
      jsonapi_swagger_helpers (~> 0.1)
      nested_attribute_reassignable (~> 0.6)
      rails (>= 4.1, < 6)
      strong_resources (~> 0.1)
    jsonapi_swagger_helpers (0.1.5)
      swagger-blocks (~> 1.3)
    kaminari (1.0.1)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.0.1)
      kaminari-activerecord (= 1.0.1)
      kaminari-core (= 1.0.1)
    kaminari-actionview (1.0.1)
      actionview
      kaminari-core (= 1.0.1)
    kaminari-activerecord (1.0.1)
      activerecord
      kaminari-core (= 1.0.1)
    kaminari-core (1.0.1)
```

**Comment by bastianl** [comment]
@richmolj adding `gem 'jsonapi-rails', require: 'jsonapi/rails'` as a dependency in my Gemfile fixed the issue, and i'm able to use `gem 'jsonapi_suite', '~> 0.5.1'`. Thanks!

**Comment by richmolj** [comment]
@bastianl I think I'm just telling you the wrong gem versions 😛  `0.5.x` is now officially released and [the docs have been updated](https://jsonapi-suite.github.io/jsonapi_suite)

**Comment by richmolj** [comment]
@bastianl please let me know any other issues! I'm updating the sample apps to the new versions now, so you'll have a reference.
